project:
  type: website

website:
  title: "kaylee03.github.io"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Map or Visualization"
        href: map.qmd
      - text: "Data"
        href: data.qmd
      - text: "Open Letter"
        href: Letter.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

